### PR TITLE
Drag And drop

### PR DESCRIPTION
**Pull request by Anonymous6598**
These files are necessary for Drag And Drop support. Don't forget to install tkinterdnd2 extension for Tkinter or Customtkinter framework. `pip install tkinterdnd2` or `pip3 install tkinterdnd2`

### CODE REVIEW

**Comment by Anonymous6598** [comment]
This is first stage of our plan. Are you ready to merge it? Or still not?

**Comment by lorenzolpandolfo** [comment]
> This is first stage of our plan. Are you ready to merge it? Or still not?

I tested your contribution but the drag and drop doesnt seem to work

**Comment by Anonymous6598** [comment]
It's still not done. Now I have to add `dnd_bind()` method. And make method for dnd.

**Comment by Anonymous6598** [comment]
Now you can try it @lorenzolpandolfo.

**Comment by Anonymous6598** [comment]
Did you install tkinterdnd2?

**Comment by Anonymous6598** [comment]
Hello @lorenzolpandolfo!
Have you tried my code?
@Anonymous6598

**Comment by lorenzolpandolfo** [comment]
> Hello @lorenzolpandolfo! Have you tried my code? @Anonymous6598

Hello, @Anonymous6598 !
Yes, I tested your code and It seems to work just fine now. Thank you for your contribution!
Also, we should remove the tkinterdnd2 local module and add it in the requeriments.txt file.

**Comment by Anonymous6598** [comment]
Your welcome.

**Comment by Anonymous6598** [comment]
Don't forget to put star on My_Diary project.

**Pull request merged**
